"""Torrent site registry."""
from torrtux_core.sites.providers import (
    ArabTorrents,
    Bitsearch,
    ETTV,
    EZTV,
    FitGirlRepacks,
    Glodls,
    GoodTorrent,
    KickassTorrents,
    LimeTorrents,
    LinuxTracker,
    MagnetDL,
    Nyaa,
    PirateBay,
    RARBG,
    SkyTorrents,
    Torlock,
    TorrentDownloads,
    TorrentFunk,
    TorrentGalaxy,
    TorrentProject,
    Torrentz2,
    X1337,
    YTS,
    YourBittorrent,
    Zooqle,
)

ALL_SITE_CLASSES = [
    PirateBay,
    X1337,
    KickassTorrents,
    YTS,
    Nyaa,
    EZTV,
    TorrentGalaxy,
    LimeTorrents,
    TorrentDownloads,
    Torlock,
    Zooqle,
    TorrentFunk,
    ETTV,
    MagnetDL,
    Bitsearch,
    Glodls,
    TorrentProject,
    SkyTorrents,
    YourBittorrent,
    GoodTorrent,
    Torrentz2,
    RARBG,
    ArabTorrents,
    FitGirlRepacks,
    LinuxTracker,
]

__all__ = [cls.__name__ for cls in ALL_SITE_CLASSES] + ["ALL_SITE_CLASSES"]
